// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGWBd9xC3Bx_7WYmIoOCzMWpGtBhn5ZEk',
    appId: '1:60110180073:web:fcb570284dba0feef06a78',
    messagingSenderId: '60110180073',
    projectId: 'secondevie-a40f0',
    authDomain: 'secondevie-a40f0.firebaseapp.com',
    storageBucket: 'secondevie-a40f0.appspot.com',
    measurementId: 'G-4XK5TNK043',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZHcdm0-aWiSdvGh80RbRatVnYmFcxm_U',
    appId: '1:60110180073:android:210b5ff73a6b551bf06a78',
    messagingSenderId: '60110180073',
    projectId: 'secondevie-a40f0',
    storageBucket: 'secondevie-a40f0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCYI0v3-mc7XCxsmb6ah9WsC57QRvA9NI',
    appId: '1:60110180073:ios:c899c1e7b060c491f06a78',
    messagingSenderId: '60110180073',
    projectId: 'secondevie-a40f0',
    storageBucket: 'secondevie-a40f0.appspot.com',
    iosBundleId: 'com.example.newAppSecondmain',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCYI0v3-mc7XCxsmb6ah9WsC57QRvA9NI',
    appId: '1:60110180073:ios:c899c1e7b060c491f06a78',
    messagingSenderId: '60110180073',
    projectId: 'secondevie-a40f0',
    storageBucket: 'secondevie-a40f0.appspot.com',
    iosBundleId: 'com.example.newAppSecondmain',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGWBd9xC3Bx_7WYmIoOCzMWpGtBhn5ZEk',
    appId: '1:60110180073:web:9a98d4755e2337a3f06a78',
    messagingSenderId: '60110180073',
    projectId: 'secondevie-a40f0',
    authDomain: 'secondevie-a40f0.firebaseapp.com',
    storageBucket: 'secondevie-a40f0.appspot.com',
    measurementId: 'G-YK9CER01K5',
  );
}
